title: "Meu Site"
description: "Descrição do meu site"
baseurl: "/mrgonso.github.io" # Subdiretório do site (use o nome do repositório)
url: "https://juniorgonso.github.io" # URL do site
theme: minima # Tema padrão do Jekyll
