title: "Meu Site"
description: "Descrição do meu site"
baseurl: "" # Subdiretório do site (deixe vazio se for a raiz)
url: "https://juniorgonso.github.io" # URL do site
theme: minima # Tema padrão do Jekyll
