name: "Lighthouse Badger"

########################################################################
# DEFINE YOUR INPUTS E TRIGGERS NO SEGUINTE
########################################################################

# INPUTS como Segredos (env) para workflows não acionados manualmente
env:
  URLS: https://juniorgonso.github.io/mrgonso.github.io/
  # Se algum dos seguintes env estiver em branco, um valor padrão será usado em vez disso
  REPO_BRANCH: "${{ github.repository }} gh-pages" # repositório e branch alvo, por exemplo, 'dummy/mytargetrepo main'
  MOBILE_LIGHTHOUSE_PARAMS: "--only-categories=performance,accessibility,best-practices,seo --throttling.cpuSlowdownMultiplier=2"
  DESKTOP_LIGHTHOUSE_PARAMS: "--only-categories=performance,accessibility,best-practices,seo --preset=desktop --throttling.cpuSlowdownMultiplier=1"

# TRIGGERS
on:
  page_build:
  # schedule: # Verifique sua programação aqui => https://crontab.guru/
  #   - cron: '55 23 * * 0' # por exemplo, todo domingo às 23:55
  workflow_dispatch:

########################################################################
# É ISSO; VOCÊ NÃO PRECISA DEFINIR NADA NO SEGUINTE
########################################################################

jobs:
  lighthouse-badger-easy:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Preparatory Tasks
        run: |
          REPOSITORY=`expr "${{ env.REPO_BRANCH }}" : "\([^ ]*\)"`
          BRANCH=`expr "${{ env.REPO_BRANCH }}" : ".* \([^ ]*\)"`
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        env:
          REPO_BRANCH: ${{ env.REPO_BRANCH }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY }}
          token: ${{ secrets.ACTIONS_PAT }}
          ref: ${{ env.BRANCH }}
      - name: Checkout Lighthouse badges
        uses: actions/checkout@v4
        with:
          repository: "myactionway/lighthouse-badges"
          path: temp_lighthouse_badges_nested
      - name: Run Lighthouse Badger Action
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ env.URLS }}
          mobile_lighthouse_params: ${{ env.MOBILE_LIGHTHOUSE_PARAMS }}
          desktop_lighthouse_params: ${{ env.DESKTOP_LIGHTHOUSE_PARAMS }}
